#!/bin/bash
#SBATCH --job-name=test_slurm # define job name
#SBATCH --nodes=1             # define node
#SBATCH --gpus-per-node=1     # define gpu limmit in 1 node
#SBATCH --ntasks=1            # define number tasks
#SBATCH --cpus-per-task=24    # There are 24 CPU cores
SBATCH --time=0-1:10:00     # Max running time = 10 minutes

nvidia-smi
echo "-----------------------------"
echo "## Print Python and cuda"


module load pytorch-extra-py39-cuda11.2-gcc9
pip install gdown
pip install transformers
python --version
python hello.py

echo "-----------------------------"
echo "SLURM_GPUS_ON_NODE=$SLURM_GPUS_ON_NODE"
echo "SLURM_GPUS_PER_NODE=$SLURM_GPUS_PER_NODE"
echo "SLURM_JOB_GPUS=$SLURM_JOB_GPUS"

echo "-----------------------------"
echo "Exit worker node"